spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_backend_demo_dev?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: java_backend_demo_dev_user
    password: secret
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

logging:
  level:
    root: warn
    org.springframework: debug
    org.hibernate: info
    com.pablozoani: debug