spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://localhost:3306/java_backend_demo_prod?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: java_backend_demo_prod_user
    password: secret
    platform: mysql
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

logging:
  file:
    name: java_backend_demo.log
  level:
    root: error
    org.springframework: error
    org.hibernate: error
    com.pablozoani: error